version: '2'
services:
  acl:
    build: .
    volumes:
      - ./:/var/www
    depends_on:
      - acl-mysql
      - acl-redis

  acl-mysql:
    image: mysql:5.7.22
    command: --innodb-use-native-aio=0
    restart: always
    ports:
      - "3306"
    volumes:
      - "./.docker/dbdata:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: acl
      MYSQL_ROOT_PASSWORD: root

  acl-nginx:
    build: ./.docker/.nginx
    restart: always
    ports:
      - "8086:80"
    volumes:
      - ./:/var/www
    depends_on:
      - acl

  acl-redis:
    image: redis:alpine
    expose:
      - 6379
